20.Б10-мм, Дегтярев Иван, hw1.3
Degiv/spbu_kotlin_homework pull request #3
Opened 2021-03-17 02:16 UTC by Degiv

2021-03-17 05:25 UTC, Degiv commented
У меня все работало, и я делал уже только коммиты, чтобы пройти чекер, и в какой-то момент у меня перестал компилироваться проект с такой ошибкой 
![image](https://user-images.githubusercontent.com/32798005/111419211-1f4cb980-86fa-11eb-977f-1851046a9220.png)

2021-03-17 05:27 UTC, Degiv commented
Я даже ничего не менял нигде кромe main(), не понимаю из-за чего эта ошибка, и как ее исправить. Гуглить пробовал

2021-03-17 13:28 UTC, nbirillo commented
Нажми File -> Invalidate caches/Restart и сбрось кэш и перезапусти идею, все заработает

2021-03-17 13:33 UTC, nbirillo requested changes

2021-03-17 13:33 UTC, nbirillo commented on src/main/kotlin/hw1/task3/Actions.kt
> +            return
Ошибку может надо кидать лучше?

2021-03-17 13:33 UTC, nbirillo commented on src/main/kotlin/hw1/task3/main.kt
> +}
У тебя эти функции очень похожи. Их можно как-то объединить?

2021-03-17 13:33 UTC, nbirillo commented on src/main/kotlin/hw1/task3/main.kt
> +    var mustContinue: Boolean = true
Можно не указывать тип, итак понятно

2021-03-17 13:33 UTC, nbirillo commented on src/main/kotlin/hw1/task3/main.kt
> +                var newValue = inputNumberToAdd()
Может тут лучше использовать val? И везде ниже тоже

2021-03-17 13:33 UTC, nbirillo commented on src/main/kotlin/hw1/task3/main.kt
> +fun main() {
![image](https://user-images.githubusercontent.com/8993915/111475615-55ac2800-873e-11eb-8c75-473fd935d8ce.png)
давай ты как-то будешь по-человечески выводить действия?

2021-03-19 08:36 UTC, nbirillo requested changes

2021-03-19 08:36 UTC, nbirillo commented on src/main/kotlin/hw1/task3/CommandStorage.kt
> +        var lastIndex: Int = commandList.lastIndex
Пояему здесь не val?

2021-03-19 08:36 UTC, nbirillo commented on src/main/kotlin/hw1/task3/main.kt
> +            val newValue = inputNumber()
Может лучше ты добавишь в функцию еще сообщение? а то ты везде еще просто print добавляешь

2021-03-19 08:36 UTC, nbirillo commented on src/main/kotlin/hw1/task3/main.kt
> +            }
Вот эти строчки у тебя повторяются дважды, тоже можно сделать функцию

2021-03-24 16:25 UTC, elena-lyulina requested changes
почти все!

2021-03-24 16:25 UTC, elena-lyulina commented on src/main/kotlin/hw1/task3/CommandStorage.kt
> +        commandList[lastIndex].undo()
один маленький комментарий, что можно сразу использовать last() вместо нахождения индекса и обращения по нему

2021-03-25 10:17 UTC, merged