20.Б10-мм, Дегтярев Иван, hw2.2
Degiv/spbu_kotlin_homework pull request #5
Opened 2021-03-24 05:07 UTC by Degiv

2021-03-24 16:17 UTC, elena-lyulina requested changes

2021-03-24 16:17 UTC, elena-lyulina commented on src/main/kotlin/hw2/task2/main.kt
> +    val numbersAsStrings: List <String> = readLine().toString().split(" ")
тут немного странно, что promt как параметр передается, так как судя по реализации у тебя все время парсится одна строка чисел, введенных через запятую, то есть кроме как "Enter your array of numbers in one line: " особо и нечего написать пользователю

2021-03-24 16:17 UTC, elena-lyulina commented on src/main/kotlin/hw2/task2/main.kt
> +    return numbers
давай ты попробуешь это в одну строчку написать и без создания дополнительного списка numbers?

2021-03-24 16:17 UTC, elena-lyulina commented on src/main/kotlin/hw2/task2/main.kt
> +    print("Your array without duplicates: ${numbers.asReversed().distinct().asReversed()}")
хочется, чтобы была отдельная функция, убирающая дупликаты, чтобы ей можно было пользоваться и в других местах, например, в тестах

2021-03-25 11:05 UTC, Degiv commented on src/main/kotlin/hw2/task2/main.kt
> +    return numbers
@elena-lyulina не понимаю как обойтись без дополнительного списка, если начальный список имеет тип String, а вернуть надо список типа Int

2021-03-25 11:12 UTC, Degiv commented on src/main/kotlin/hw2/task2/main.kt
> +    return numbers
@elena-lyulina не понимаю как обойтись без дополнительного списка, если начальный список имеет тип String, а вернуть надо список типа Int

2021-03-25 11:13 UTC, Degiv commented on src/main/kotlin/hw2/task2/main.kt
> +    return numbers
если поэлеметно привести к Int, сам список же так и будет считать типа String

2021-03-25 11:20 UTC, Degiv commented on src/main/kotlin/hw2/task2/main.kt
> +    return numbers
окей, я что-то придумал, не знаю насколько это правильно

2021-03-25 11:42 UTC, Degiv commented on src/main/kotlin/hw2/task2/main.kt
> +    return numbers
@elena-lyulina я попробовал так, но вылезает ошибка, якобы каст без проверки, хотя как-будто проверка есть
`return readLine().toString().split(" ") as? List <Int> ?: error("Incorrect input.")`

2021-03-25 11:59 UTC, Degiv commented on src/main/kotlin/hw2/task2/main.kt
> +    return numbers
я пока залью те исправления, что сделал

2021-03-25 12:12 UTC, Degiv commented on src/main/kotlin/hw2/task2/main.kt
> +    return numbers
я что-то сделал, но не уверен, что это имелось в виду

2021-03-25 13:46 UTC, elena-lyulina commented on src/main/kotlin/hw2/task2/main.kt
> +    return numbers
ну смотри, ты итерируешься по numbersAsString, каждый из элементов которого ты переводишь в Int или выводишь ошибку, создавая таким образом список из Int
я предлагаю попробовать сделать это, не заводя дополнительно списка numbers и не используя цикл for
писать тебе целиком ответ я не буду, но попробуй использовать map на numbersAsString :)

2021-03-25 13:57 UTC, Degiv commented on src/main/kotlin/hw2/task2/main.kt
> +    return numbers
@elena-lyulina то есть то как я сейчас сделал не подходит? 
`val numbers = mutableListOf<Int>()
    readLine().toString().split(" ").forEach { numbers.add(it.toIntOrNull() ?: error("Incorrect input.")) }
    return numbers`

2021-03-25 14:11 UTC, elena-lyulina commented on src/main/kotlin/hw2/task2/main.kt
> +    return numbers
ну, это выглядит странным, если честно

2021-03-25 14:12 UTC, elena-lyulina commented on src/main/kotlin/hw2/task2/main.kt
> +    return numbers
и так обычно не пишут

2021-03-25 14:14 UTC, elena-lyulina commented on src/main/kotlin/hw2/task2/main.kt
> +    return numbers
то есть вполне можно опустить создание numbersAsString, окей, хотя это чуть перегружает логику этой строчки, и итерироваться сразу по результату split()

но вот создавать список numbers и в другом списке туда что-то добавлять -- вот так не пишут, так как ты можеш сразу мапнуть каждый элемент предыдущего списка в нужный тебе элемент

2021-03-25 14:15 UTC, elena-lyulina commented on src/main/kotlin/hw2/task2/main.kt
> +    return numbers
короче, просто попробуй использовать map и поймешь, что я имею в виду :)

2021-03-26 04:38 UTC, elena-lyulina approved these changes

2021-03-26 04:39 UTC, elena-lyulina commented
Здорово, спасибо

2021-03-26 04:39 UTC, merged